// import { Inter } from "next/font/google";
// import "./globals.css";
// import Sidebar from "@/component/Sidebar/Sidebar";
// import Navbar from "@/component/Navbar/Navbar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className} style={{ overflowY: "auto" }}>
//         <div className="flex h-screen overflow-hidden">
//           <div className="w-64 bg-gray-800 text-white flex-shrink-0">
//             <Sidebar />
//           </div>

//           <div className="flex flex-col flex-1 overflow-hidden">
//             <Navbar />
//             <div className="flex-1 overflow-y-auto p-4">{children}</div>
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }
"use client"
import { Inter } from "next/font/google";
import { useState } from "react";
import "./globals.css";
import Sidebar from "@/component/Sidebar/Sidebar";
import Navbar from "@/component/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isExpanded, setIsExpanded] = useState(false);

  const toggleSidebar = () => {
    setIsExpanded(!isExpanded);
  };

  console.log("isExpanded",isExpanded);

  return (
    <html lang="en">
      <body className={inter.className} style={{ overflowY: "auto" }}>
        <div className="flex h-screen overflow-hidden">
          <div className={`bg-gray-800 text-white flex-shrink-0 transition-all duration-300 ${isExpanded ? 'w-16' : 'w-2/12'}`}>
            <Sidebar isExpanded={isExpanded}/>
          </div>

          <div className="flex flex-col flex-1 overflow-hidden">
            <Navbar toggleSidebar={toggleSidebar} />
            
            <div className="flex-1 overflow-y-auto p-4" >{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
